version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENVIRONMENT: "dev"
    ports:
      - 8081:8081
    env_file: ./app.env

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    ports:
      - "8080:8978"

volumes:
    persistent-development-extensions: