version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENVIRONMENT: "dev"
    ports:
      - 8081:8081
    env_file: ./app.env

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
    persistent-development-extensions: