version: '3.8'
services: 
  app:
    volumes:
      - .:/workspace:cache
      - persistent-development-extensions:/home/userapp/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"